name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6.3
      - name: Install dependencies
        run: bundle install
      - name: Run DB migration
        run : rake db:migrate RAILS_ENV=test
      - name: Adding Bootstrap, jquery and popper.js
        run : yarn add bootstrap jquery popper.js
      - name: Run tests
        run: bundle exec rake